### PR TITLE
Ohdeargodwhy

### PR DESCRIPTION
**Pull request by Draconic-saint**
WAIT, I THINK I GOT THIS, I THINK I FINALLY GOT THIS, RIP ALL THE PUPPIES IF I FUCK THIS UP

### CODE REVIEW

**Comment by Draconic-saint** [comment]
So this is the way to get this thing up to date the legit way I think? I dunno, but resolving that 1k commit backlog can't be bad I guess, if I could resolve the conflicts, that is.

**Comment by Crazylemon64** [comment]
RIP ALL THE PUPPIES

**Comment by Crazylemon64** [comment]
I mean, I'm not sure why your commit log is so NOISY

Try `git pull upstream master`, manually fixing all the ">>>>>" bits in conflicted files (found by using `git status`), and then using `git add` on each file you fixed a merge conflict in. Then, a `git commit` SHOULD yield a single-commit thing that isn't a 50-page monstrosity that will rip all the puppies.

**Comment by Draconic-saint** [comment]
So just close this pr and try again?

**Comment by Crazylemon64** [comment]
Oh, also, I guess we ARE going to have 1000+ commits here, since we're working on a separate branch of paradise...

**Comment by Draconic-saint** [comment]
Also, these command line instructions aren't very clear about step 2.2 how do I confirm the merge?

**Comment by Draconic-saint** [comment]
IT WORKEDED, now do I merge this?

**Comment by Crazylemon64** [comment]
I guess you do!

**Pull request merged**
